[common]
platform = espressif32@6.7.0
board = esp32dev
framework = espidf
monitor_speed = 115200
upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001
lib_deps = someweisguy/esp_dmx@^4.1.0

[env:wakelight]
extends = common
src_dir = src

[env:diagnostic]
extends = common
src_dir = diagnostic
